Задача 1 к Уроку 2
Akullaaa/KotlinSprint pull request #6
Opened 2024-03-10 20:50 UTC by Akullaaa

Задача на среднее арифметическое. В классе с углубленным изучением английского языка учится 4 человека. У них следующие баллы по профильному предмету 3, 4, 3, 5. Пишем часть школьного софта, который посчитает средний балл по английскому для этого класса. 

 – Написать выражение, которое высчитывает средний балл;
 – Распечатать результат в консоль;
 – В консоли должно быть выведено дробное число с 2 знаками после запятой.

2024-03-11 08:48 UTC, ievetrovdev requested changes

2024-03-11 08:48 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task1.kt
> +	val amountOfPoints = 3 + 4 + 3 + 5
Все не плохо, но если в условии даны те или иные значения их нужно инициализировать с релевантными названиями, тогда они не будут [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), кроме того, человеку, первый раз увидевшему код, сложно будет разобраться

2024-03-11 08:48 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task1.kt
> +	val averageScore = amountOfPoints.toFloat() / studentsCount
Тут напрашивается обособление пустыми строками принт (сверху тоже)

2024-03-11 08:55 UTC, Akullaaa commented on src/main/kotlin/lesson2/lesson2_task1.kt
> +	val amountOfPoints = 3 + 4 + 3 + 5
Подумаю над новым названием переменной

2024-03-11 08:56 UTC, Akullaaa commented on src/main/kotlin/lesson2/lesson2_task1.kt
> +	val averageScore = amountOfPoints.toFloat() / studentsCount
А вот тут не совсем понял что именно обособлять? И чем? Пустыми строками или оператором принт с пустыми строками?

2024-03-12 14:53 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task1.kt
> +	val averageScore = amountOfPoints.toFloat() / studentsCount
Визуально код выглядит лучше, когда переменные отделены от принта, не ошибка, но на больших проектах повышает читабельность)

2024-03-12 14:53 UTC, ievetrovdev approved these changes
Все отлично!

2024-03-16 11:14 UTC, merged